#!/bin/bash

set -e

declare DRIVER_NAME="@@@DRIVER_NAME@@@"
declare DRIVER_VERSION="@@@DRIVER_VERSION@@@"

if test "$1" == "remove" || test "$1" == "upgrade" || test "$1" == "deconfigure"; then
  if test "$(sudo dkms status -m $DRIVER_NAME -v DRIVER_VERSION)"; then
    dkms remove -m acer-nitro17 -v $DRIVER_VERSION --all
  fi
fi

unset DRIVER_NAME
unset DRIVER_VERSION

exit 0
